name: Release
on:
    release:
        [published, released]
jobs:
    ubuntu:
        name: Ubuntu Build
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v2
            - name: Rust Stable
              uses: actions-rs/toolchain@v1
              with:
                  profile: minimal
                  toolchain: stable
            - name: Build
              uses: actions-rs/cargo@v1
              with:
                  command: build
                  args: --release
            - name: Upload artifact
              uses: actions/upload-artifact@v2
              with:
                  name: rust-template-linux
                  path: target/release/rust-template
    windows:
        name: Windows Build
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v2
            - name: Rust Stable
              uses: actions-rs/toolchain@v1
              with:
                  profile: minimal
                  toolchain: stable
            - name: Build
              uses: actions-rs/cargo@v1
              with:
                  command: build
                  args: --release
            - name: Upload artifact
              uses: actions/upload-artifact@v2
              with:
                  name: rust-template-windows.exe
                  path: target/release/rust-template.exe
